trigger:
- main # Trigger on pushes to the main branch (adjust if needed)

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if you prefer

variables:
  azureSubscription: 'Visual Studio Professional Subscription' # Name in Azure DevOps
  webAppName: 'whoamai-ak' 
  publishOutputFolder: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Or your desired .NET version

- task: DotNetCoreCLI@2
  displayName: 'Restore'