
pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if you prefer

variables:
  azureSubscription: '<NAME_OF_YOU_ADO_SERVICE_CONNECTION>' # Name in Azure DevOps
  webAppName: '<NAME_OF_YOUR_WEB_APPLICATION>' 
  publishOutputFolder: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Or your desired .NET version

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: '-c Release -o $(publishOutputFolder)'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: $(webAppName)'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(webAppName)
    package: $(publishOutputFolder)/**/*.zip